#!/bin/bash

action=$1
target=$2

usage() {
    cat <<-EOF
    usage : $0 action target
    available actions:
        backup
        restore
    available targets:
        db
EOF

    exit 0
}

cd /tmp

wazo_backup() {
    case $target in
        db) wazo_backup_db;;
        *) usage;;
    esac
}

wazo_restore() {
    case $target in
        db) wazo_restore_db;;
        *) usage;;
    esac
}

wazo_backup_db() {
    wazo-service stop
    service postgresql restart
    wazo-backup db db
    wazo-service start
}

wazo_restore_db() {
    wazo-service stop
    tar xvf db.tgz -C /tmp
    cd /tmp/pg-backup
    service postgresql restart
    sudo -u postgres dropdb asterisk
    sudo -u postgres pg_restore -C -d postgres asterisk-*.dump
    sudo -u postgres dropdb xivo
    sudo -u postgres pg_restore -C -d postgres xivo-*.dump
    wazo-auth-keys service update --recreate
    wazo-auth-keys service clean --users
    XIVO_UUID=$(sudo -u postgres psql -d asterisk -tA -c 'select uuid from infos')
    echo "export XIVO_UUID=$XIVO_UUID" > /etc/profile.d/xivo_uuid.sh
    sed -i "s/DefaultEnvironment=.*/DefaultEnvironment=\"XIVO_UUID=$XIVO_UUID\"/" /etc/systemd/system.conf
    source /etc/profile.d/xivo_uuid.sh
    systemctl set-environment XIVO_UUID=$XIVO_UUID
    systemctl daemon-reload
    wazo-service start
}

case $action in
    backup)     wazo_backup;;
    restore)    wazo_restore;;
    *)          usage;;
esac
