[tool.flake8]
show-source = true
max-line-length = 99
application-import-names = "wazo_acceptance"
ignore = [
  "E203", # whitespace before ':'
  "E501", # line too long (80 chars)
  "W503", # line break before binary operator
]
exclude = [
    ".tox",
]

[tool.isort]
profile = "black"
py_version = 311

[tool.coverage.report]
exclude_also = [
    "if command_result.returncode != 0:",
    "if exception:",
    "if TYPE_CHECKING:",
    "except LinphoneException",
    "raise AssertionError",
    "raise Exception",
    "raise NotImplementedError",
]
