# -*- coding: utf-8 -*-
# Copyright 2013-2018 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0+

from xivo_acceptance.lettuce import terrain

from .admin_user_steps import *
from .agent_list_steps import *
from .agent_steps import *
from .agid_steps import *
from .application_steps import *
from .asterisk_steps import *
from .backup_steps import *
from .call_logs_steps import *
from .call_steps import *
from .callfilter_steps import *
from .certificate_steps import *
from .chat_steps import *
from .common_webi_steps import *
from .common_xivoclient_steps import *
from .common_bus_steps import *
from .conf_file_steps import *
from .configfiles_steps import *
from .configuration_steps import *
from .consul_steps import *
from .context_steps import *
from .cti_client_steps import *
from .cti_client_configuration_steps import *
from .cti_profiles_steps import *
from .cti_server_steps import *
from .ctid_client_steps import *
from .device_steps import *
from .dhcpd_steps import *
from .directory_steps import *
from .entity_steps import *
from .extensions_steps import *
from .fail2ban_steps import *
from .files_steps import *
from .funckeys_steps import *
from .general_settings_sccp_steps import *
from .general_settings_xivo_steps import *
from .group_steps import *
from .ha_steps import *
from .http_steps import *
from .incall_steps import *
from .ivr_steps import *
from .ipbx_count_steps import *
from .ldap_steps import *
from .line_extension_steps import *
from .line_steps import *
from .meetme_steps import *
from .outcall_steps import *
from .parking_steps import *
from .phonebook_steps import *
from .pickup_steps import *
from .profile_steps import *
from .provd_plugins_steps import *
from .provd_proxy_steps import *
from .queue_steps import *
from .schedule_steps import *
from .service_extensions import *
from .sheet_steps import *
from .skillrules_steps import *
from .statcenter_steps import *
from .supervisor_steps import *
from .switchboard_steps import *
from .system_steps import *
from .trunk_custom_steps import *
from .trunk_iax_steps import *
from .trunk_sip_steps import *
from .user_line_steps import *
from .user_steps import *
from .user_forward_steps import *
from .user_service_steps import *
from .voicemail_steps import *
from .webi_login_steps import *
from .wizard_steps import *
from .xivo_agent_steps import *
from .xlet_identity_steps import *
from .xlet_queue_member_steps import *
from .xlet_service_steps import *
