#!/bin/bash

case $1 in
    config)
        cat <<'EOM'
graph_title XIVO ASTERISK file descriptors
graph_vlabel File descriptors count
asteriskfiledesc.label Nb of Asterisk file descriptors
asteriskfiledesc.draw AREA
EOM
        exit 0;;
esac

echo -n "asteriskfiledesc.value "; /usr/bin/lsof | grep -c asterisk

exit 0
