#!/bin/bash

case $1 in
    config)
        cat <<'EOM'
graph_title XIVO CTID Memory usage
graph_vlabel Bytes
graph_category xivo
ctidmem.label CTID Memory
ctidmem.draw AREA
EOM
        exit 0;;
esac

raw_mem=`/bin/ps axu | grep -e '/usr/bin/xivo-ctid' | grep -v 'grep' | awk -F" " '{print $6}'`
mem=$(( $raw_mem / 1024 ))
echo "ctidmem.value" ${mem}

exit 0
