#!/bin/bash

case $1 in
    config)
        cat <<'EOM'
graph_title XIVO ASTERISK Memory usage
graph_vlabel Bytes
graph_category xivo
asteriskmem.label Asterisk memory
asteriskmem.draw AREA
asteriskmem_vsz.label Asterisk virtual memory
asteriskmem_vsz.draw LINE
EOM
        exit 0;;
esac

raw_resv_mem=`/bin/ps axu | grep -e '/usr/sbin/asterisk' | grep -v 'grep' | awk -F" " '{print $6}'`
raw_virt_mem=`/bin/ps axu | grep -e '/usr/sbin/asterisk' | grep -v 'grep' | awk -F" " '{print $5}'`
resv_mem=$(( $raw_resv_mem / 1024 ))
virt_mem=$(( $raw_virt_mem / 1024 ))
echo "asteriskmem.value" ${resv_mem}
echo "asteriskmem_vsz.value" ${virt_mem}

exit 0
