#!/bin/bash

action=$1

usage() {
    cat <<-EOF
    usage : $0 action
    availables actions :
        backup  : execute backup
        restore : execute restore
EOF

    exit 0
}

cd /tmp

xivo_backup() {
    xivo-service stop
    service postgresql restart
    xivo-backup db db
    xivo-service start
}

xivo_restore() {
    xivo-service stop
    tar xvf db.tgz -C /tmp
    cd /tmp/pg-backup
    service postgresql restart
    sudo -u postgres dropdb asterisk
    sudo -u postgres pg_restore -C -d postgres asterisk-*.dump
    sudo -u postgres dropdb xivo
    sudo -u postgres pg_restore -C -d postgres xivo-*.dump
    xivo-service start
}

case $action in
    backup)     xivo_backup;;
    restore)    xivo_restore;;
    *)          usage;;
esac
