# -*- coding: UTF-8 -*-

from xivo_lettuce import terrain

from agent_steps import *
from asterisk_steps import *
from backup_steps import *
from call_steps import *
from certificate_steps import *
from common_callgen_steps import *
from common_webi_steps import *
from common_xivoclient_steps import *
from conf_file_steps import *
from configfiles_steps import *
from cti_server_steps import *
from device_steps import *
from dhcpd_steps import *
from directed_pickup_steps import *
from file_steps import *
from files_steps import *
from general_settings_iax_steps import *
from general_settings_sccp_steps import *
from general_settings_sip_steps import *
from general_settings_xivo_steps import *
from group_steps import *
from incall_steps import *
from ipbx_count_steps import *
from ldap_steps import *
from line_steps import *
from meetme_steps import *
from outcall_steps import *
from parking_steps import *
from phonebook_steps import *
from profile_steps import *
from provd_plugins_steps import *
from provd_proxy_steps import *
from queue_steps import *
from sheet_steps import *
from skillrules_steps import *
from statcenter_steps import *
from supervisor_steps import *
from trunk_custom_steps import *
from trunk_iax_steps import *
from trunk_sip_steps import *
from user_import_steps import *
from user_steps import *
from voicemail_steps import *
from wizard_steps import *
from xlet_identity_steps import *
from xlet_queue_member_steps import *
