# -*- coding: UTF-8 -*-

from lettuce.decorators import step
from xivo_lettuce import sysutils


@step(u'Then cti configuration file correctly generated')
def then_cti_configuration_file_correctly_generated(step):
    CTI_INI_FILE = '/etc/pf-xivo/web-interface/cti.ini'
    CTI_INI_CONTENT_RESULT = """\
; XIVO: FILE AUTOMATICALLY GENERATED BY THE XIVO CONFIGURATION SUBSYSTEM
[general]
datastorage = "postgresql://xivo:proformatique@localhost/xivo?encoding=utf8"

[queuelogger]
datastorage = "postgresql://asterisk:proformatique@localhost/asterisk?charset=utf8"

"""
    cti_ini_content = sysutils.get_content_file(CTI_INI_FILE)
    assert cti_ini_content == CTI_INI_CONTENT_RESULT
