#!/bin/bash

GIT_ROOT="git://git.xivo.fr/official"
REPOSITORIES="xivo-dao xivo-acceptance xivo-lib-python xivo-dird xivo-restapi xivo-provisioning"
PYTHONPATH_STR=''
FEATURE_NAME=$(echo $JOB_NAME | sed 's/acceptance_//g')

export PYTHONIOENCODING=UTF-8
export XC_PATH=/tmp/cticlient_bin

function clone_or_pull_repo() {
    repo="$1"
    if [ ! -d "$repo" ]; then
        git clone $GIT_ROOT/$repo.git .
    else
        cd $repo
        git pull
        git fetch -p
        cd ..
    fi
}

for repo in $REPOSITORIES ; do
    repo_path="/data/$repo"
    echo "processing $repo ..."
    cd $repo_path
    clone_or_pull_repo $repo

    if [ $repo == 'xivo-acceptance' ]; then
        PYTHONPATH_STR="${PYTHONPATH_STR}:/data/${repo}
    else
        extra=''
        if [ $repo == 'xivo-provisioning' ]; then
            extra='/src'
        fi
        PYTHONPATH_STR="${PYTHONPATH_STR}:/data/${repo}/${repo}${extra}"
    fi
done

export PYTHONPATH=$PYTHONPATH_STR

if [ $FEATURE_NAME == 'post_wizard' ]; then
    python /data/xivo-acceptance/utils/prerequisite.py
fi

cd /data/xivo-acceptance/
cp -r features/$FEATURE_NAME $WORKSPACE

cd $WORKSPACE
lettuce $FEATURE_NAME --with-xunit --verbosity=3 --xunit-file=xunit-tests.xml
cp xunit-tests.xml /data/test_results/$JOB_NAME.xml
