#!/bin/bash

REPO_DIR='/data'
GIT_ROOT="git://github.com/xivo-pbx"
REPOSITORIES="pylinphonelib xivo-bus xivo-dao xivo-acceptance xivo-lib-python xivo-dird xivo-restapi xivo-provisioning"
PYTHONPATH_STR=''
FEATURE_NAME=$(echo $JOB_NAME | sed 's/acceptance_//g')

export PYTHONIOENCODING=UTF-8

function clone_or_pull_repo() {
    repo="$1"
    cd $REPO_DIR
    if [ ! -d "$repo" ]; then
        git clone $GIT_ROOT/$repo.git
    else
        cd $repo
        git pull
        git fetch -p
    fi
}

for repo in $REPOSITORIES ; do
    echo "processing $repo ..."
    clone_or_pull_repo $repo

    PYTHONPATH_STR="${PYTHONPATH_STR}:${REPO_DIR}/${repo}"
done

export PYTHONPATH=$PYTHONPATH_STR

if [ $FEATURE_NAME == 'post_wizard' ]; then
    python ${REPO_DIR}/xivo-acceptance/utils/prerequisite.py
fi

cd ${REPO_DIR}/xivo-acceptance
cp -r features/$FEATURE_NAME $WORKSPACE

cd $WORKSPACE
lettuce $FEATURE_NAME --with-xunit --verbosity=3 --xunit-file=xunit-tests.xml
cp xunit-tests.xml ${REPO_DIR}/test_results/$JOB_NAME.xml
