#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# Copyright (C) 2013-2014 Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Checks if XiVO is correctly installed on remote XIVO_HOST
# Usage : $0 XIVO_HOST
# Exit status is 0 if XiVO is properly installed on remote XIVO_HOST, 1 otherwise

xivo_host="$1"

function xivo_is_installed () {
    xivo_install_status="$(ssh $xivo_host /usr/bin/dpkg-query -W '-f=\${Status}\\n' xivo 2> /dev/null)"
    [ "$xivo_install_status" = "install ok installed" ]
}

function packaging_errors () {
    ssh $xivo_host apt-get install -fs -qq
}

if ! xivo_is_installed ; then
    echo "Package xivo is not installed"
    exit 1
fi

packaging_errors="$(packaging_errors)"
if [ -n "$packaging_errors" ] ; then
    echo "Packaging errors:"
    echo "$packaging_errors"
    exit 1
fi

exit 0
