#!/usr/bin/env python

import argparse
import urllib2
import json

TRAVIS_API_URL = 'https://api.travis-ci.org/repositories/xivo-pbx'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('package', help='Package name to test')

    args = parser.parse_args()

    try:
        response = urllib2.urlopen('%s/xivo-%s.json' % (TRAVIS_API_URL, args.package))
    except urllib2.HTTPError:
        print 'Error: package %s does not exist on travis' % args.package
    else:
        infos_package = json.load(response)

        if infos_package['last_build_status'] == 0:
            print 'OK'
        else:
            print 'KO'


if __name__ == '__main__':
    main()
