#!/bin/bash

usage() {
    echo "Usage: $0 [-p] feature_filename"
    echo
    echo "Options:"
    echo "  -p  only print the list of scenarios, do not run them"
    echo "  -h  print this help"
    exit 1
}

print_scenarios() {
    local file=$1
    grep -i 'scenario\( outline\)\?:' $file | sed 's/^ *Scenario\( Outline\)\?: *//gI' | awk '{print NR " - " $file}'
}

execute_scenario() {
    local file=$1
    read -p 'Which scenario do you want to run ? number: ' number
    lettuce $file -s${number}
}

RUN_LETTUCE=1

while getopts ":hp" opt; do
    case "$opt" in
        p)
            RUN_LETTUCE=0
            ;;
        h)
            usage
            ;;
        \?)
            usage
            ;;
        esac
done

feature_filename=${@:$OPTIND}

if [ -z "$feature_filename" ]; then
	usage
fi

print_scenarios $feature_filename

if [ $RUN_LETTUCE = 1 ]; then
    execute_scenario $feature_filename
fi
