---
- name: Pre-flight checks
  hosts: all
  become: true
  roles:
    - role: preflight-checks

- name: Upgrade Debian
  hosts:
    - database
    - b2bua
    - engine_api
  become: true
  roles:
    - role: debian-upgrade-first

- name: Setup DB
  hosts:
    - database
  become: true
  roles:
    - role: wazo-db

- name: Setup back-to-back user agent
  hosts: b2bua
  become: true
  roles:
    - role: b2bua

- name: Setup API Engine
  hosts: engine_api
  become: true
  roles:
    - role: engine-api
    - role: engine-api-init
    - role: uc-engine

- name: Setup UI
  hosts: uc_ui
  become: true
  roles:
    - role: uc-ui
